import { area, disease, inSeason, pest, province, rainFrequency, region, riceType, waterLevel } from "./variables.js";
import { ScorerBuilder, Scorer } from "./scorer.js";

/**
 * Get a list
 * @param {*} factor An object contains fields describing each factor
 * 					 that affect the breed of rice to plant.
 * @return {RiceBreed[]} A list of object containing the name of the rice breed and its rated score
 */
export function getRiceScoreList(factor) {

  let scoreList = []
  let scorers = riceScorers.get(factor.riceType)

  scorers.forEach((scorer, name) => {
    let score = scorer.score(factor)
    scoreList.push(new RiceBreed(name, score))
  })

  return scoreList

}

export class RiceBreed {
  /**
   * Create a rice breed
   * @param {String} name A name of the rice's breed
   * @param {Number} score A score of this rice's breed
   */
  constructor(name, score) {
    this.name = name
    this.score = score
  }
}

// Map[riceType -> Map[ riceBreed, scorer ]]
const riceScorers = new Map()

/**
 * Add a rule for a single rice breed to use in rice suggestion
 * @param {String} name The name of the rice
 * @param {String} type The type of the rice. 
 * @param {Scorer} scorer The scorer of the rice, created by invoking `scorer()`
 * @see riceType in `expert_system/variable.js`
 */
function addRice(name, type, scorer) {
  if (!riceScorers.has(type)) {
    riceScorers.set(type, new Map())
  }
  let map = riceScorers.get(type)
  map.set(name, scorer)
}

// shorthand for creating a new scorer
function scorer() {
  return new ScorerBuilder()
}

addRice("กข 1", riceType.paddy, scorer()
  .add({ area: area.irrigatedLowland }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ pest: pest.greenLeafhopper }, 1)
  .add({ disease: disease.brownSpot }, 1)
  .add({ inSeason: inSeason.no }, 1)
  .build()
)

addRice("กข 12 (หนองคาย 80)", riceType.sticky, scorer()
  .add({ either: [{ area: area.rainfedLowland }, { area: area.upland }] }, 1)
  .add({ waterLevel: waterLevel.low }, 1)
  .add({ either: [{ disease: disease.blast }, { disease: disease.brownSpot }] }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("กข 41", riceType.paddy, scorer()
  .add({ area: area.irrigatedLowland }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ region: region.north }, 1)
  .add({ pest: pest.brownPlanthopper }, 1)
  .add({ disease: disease.blast }, 1)
  .add({ inSeason: inSeason.no }, 1)
  .build()
)

addRice("กข 43", riceType.paddy, scorer()
  .add({ area: area.irrigatedLowland }, 1)
  .add({ not: { province: province.phitsanulok } }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ disease: disease.brownSpot }, 1)
  .add({ inSeason: inSeason.no }, 1)
  .build()
)

addRice("กข 47", riceType.paddy, scorer()
  .add({ area: area.irrigatedLowland }, 1)
  .add({ region: region.north }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ pest: pest.brownPlanthopper }, 1)
  .add({ disease: disease.blast }, 1)
  .add({ inSeason: inSeason.no }, 1)
  .build()
)

addRice("กข 49", riceType.paddy, scorer()
  .add({ area: area.irrigatedLowland }, 1)
  .add({ either: [{ region: region.north }, { region: region.middle }] }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ pest: pest.brownPlanthopper }, 1)
  .add({ disease: disease.blast }, 1)
  .add({ inSeason: inSeason.no }, 1)
  .build()
)

addRice("กข 57", riceType.paddy, scorer()
  .add({ area: area.irrigatedLowland }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ province: province.phetchaburi }, 1)
  .add({ pest: pest.brownPlanthopper }, 1)
  .add({ inSeason: inSeason.no }, 1)
  .build()
)

addRice("กข 6", riceType.sticky, scorer()
  .add({ area: area.rainfedLowland }, 1)
  .add({ either: [{ region: region.north }, { region: region.northeast }] }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ disease: disease.brownSpot }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("กข 61", riceType.paddy, scorer()
  .add({ area: area.irrigatedLowland }, 1)
  .add({ either: [{ region: region.north }, { region: region.middle }] }, 1)
  .add({ waterLevel: waterLevel.high }, 1)
  .add({ either: [{ pest: pest.brownPlanthopper }, { pest: pest.whitebackPlanthopper }] }, 1)
  .add({ disease: disease.blast }, 1)
  .add({ either: [{ inSeason: inSeason.yes }, { inSeason: inSeason.no }] }, 1)
  .build()
)

addRice("กข 63", riceType.paddy, scorer()
  .add({ area: area.irrigatedLowland }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ either: [{ region: region.north }, { region: region.middle }, { region: region.northeast }] }, 1)
  .add({ pest: pest.brownPlanthopper }, 1)
  .add({ inSeason: inSeason.no }, 1)
  .build()
)

addRice("กข 65", riceType.paddy, scorer()
  .add({ area: area.upland }, 1)
  .add({ region: region.north }, 1)
  .add({ waterLevel: waterLevel.low }, 1)
  .add({ pest: pest.brownPlanthopper }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("กข 69", riceType.paddy, scorer()
  .add({ either: [{ area: area.irrigatedLowland }, { area: area.rainfedLowland }] }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ disease: disease.blast }, 1)
  .add({ inSeason: inSeason.no }, 1)
  .build()
)

addRice("กข 71", riceType.paddy, scorer()
  .add({ area: area.irrigatedLowland }, 1)
  .add({ either: [{ region: region.north }, { region: region.middle }] }, 1)
  .add({ waterLevel: waterLevel.high }, 1)
  .add({ either: [{ inSeason: inSeason.yes }, { inSeason: inSeason.no }] }, 1)
  .build()
)

addRice("กข 81", riceType.paddy, scorer()
  .add({ area: area.irrigatedLowland }, 1)
  .add({ either: [{ region: region.north }, { region: region.middle }] }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ inSeason: inSeason.no }, 1)
  .build()
)

addRice("กข 83", riceType.paddy, scorer()
  .add({ either: [{ area: area.irrigatedLowland }, { area: area.rainfedLowland }] }, 1)
  .add({ region: region.northeast }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ disease: disease.blast }, 1)
  .add({ either: [{ inSeason: inSeason.yes }, { inSeason: inSeason.no }] }, 1)
  .build()
)

addRice("กข-แม่โจ้ 2", riceType.sticky, scorer()
  //.add({ area: area.no data here }, 1)
  .add({ region: region.north }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ either: [{ inSeason: inSeason.yes }, { inSeason: inSeason.no }] }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("กข 15", riceType.paddy, scorer()
  .add({ area: area.rainfedLowland }, 1)
  .add({ region: region.northeast }, 1)
  .add({ waterLevel: waterLevel.low }, 1)
  .add({ disease: disease.brownSpot }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("กข 35 (รังสิต 80)", riceType.paddy, scorer()
  .add({ area: area.rainfedLowland }, 1)
  .add({ region: region.middle }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ pest: pest.whitebackPlanthopper }, 1)
  .add({ disease: disease.bacterialBlight }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("กข 5", riceType.paddy, scorer()
  .add({ either: [{ area: area.irrigatedLowland }, { area: area.deepwater }] }, 1)
  .add({ waterLevel: waterLevel.high }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("กข 51", riceType.paddy, scorer()
  .add({ area: area.rainfedLowland }, 1)
  .add({ either: [{ region: region.north }, { region: region.northeast }] }, 1)
  .add({ waterLevel: waterLevel.high }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("กข 59", riceType.paddy, scorer()
  .add({ either: [{ area: area.rainfedLowland }, { area: area.highland }] }, 1)
  .add({ region: region.north }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("กข 73", riceType.paddy, scorer()
  .add({ region: region.northeast }, 1)
  .add({ waterLevel: waterLevel.low }, 1)
  .add({ disease: disease.blast }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("กข 75", riceType.paddy, scorer()
  .add({ either: [{ area: area.upland }, { area: area.rainfedLowland }] }, 1)
  .add({ region: region.northeast }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ disease: disease.blast }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("กข 79", riceType.paddy, scorer()
  .add({ area: area.irrigatedLowland }, 1)
  .add({ either: [{ region: region.north }, { region: region.middle }] }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("กำผาย 15", riceType.sticky, scorer()
  .add({ either: [{ area: area.irrigatedLowland }, { area: area.rainfedLowland }] }, 1)
  .add({ region: region.north }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("ขาวดอกมะลิ 105", riceType.paddy, scorer()
  .add({ area: area.rainfedLowland }, 1)
  .add({ either: [{ region: region.north }, { region: region.northeast }] }, 1)
  .add({ waterLevel: waterLevel.low }, 1)
  .add({ pest: pest.nematodes }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("ชุมแพ 60", riceType.paddy, scorer()
  .add({ area: area.rainfedLowland }, 1)
  .add({ region: region.northeast }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("ปทุมธานี 1", riceType.paddy, scorer()
  .add({ area: area.irrigatedLowland }, 1)
  .add({ region: region.middle }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ pest: pest.xxx }, 1)
  .add({ either: [{ pest: pest.brownPlanthopper }, { pest: pest.whitebackPlanthopper }] }, 1)
  .add({ either: [{ disease: disease.blast }, { disease: disease.bacterialBlight }] }, 1)
  .add({ inSeason: inSeason.no }, 1)
  .build()
)

addRice("เผือกน้ำ 43", riceType.paddy, scorer()
  //.add({ area: area.no data here }, 1)
  .add({ region: region.south }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ disease: disease.brownSpot }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("พัทลุง 60", riceType.paddy, scorer()
  .add({ area: area.rainfedLowland }, 1)
  .add({ either: [{ province: province.nakhonSiThammarat }, { province: province.satun }, { province: province.phatthalung }, { province: province.songkhla }, { province: province.pattani }] }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("พิษณุโลก 2", riceType.paddy, scorer()
  .add({ area: area.irrigatedLowland }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ either: [{ pest: pest.brownPlanthopper }, { pest: pest.whitebackPlanthopper }, { pest: pest.greenLeafhopper }] }, 1)
  .add({ inSeason: inSeason.no }, 1)
  .build()
)

addRice("พิษณุโลก 3", riceType.paddy, scorer()
  .add({ either: [{ area: area.irrigatedLowland }, { area: area.rainfedLowland }] }, 1)
  .add({ region: region.north }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ disease: disease.blast }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("หอมกระดังงา 59", riceType.paddy, scorer()
  .add({ area: area.rainfedLowland }, 1)
  .add({ either: [{ province: province.nakhonSawan }, { province: province.uthaiThani }] }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("เหมยนอง 62 เอ็ม", riceType.sticky, scorer()
  //.add({ area: area.none }, 1)
  .add({ region: region.north }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ pest: pest.riceGallMidge }, 1)
  .add({ either: [{ disease: disease.brownSpot }, { disease: disease.riceTungro }] }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("ตะเภาแก้ว 161", riceType.paddy, scorer()
  .add({ area: area.floating }, 1)
  .add({ region: region.middle }, 1)
  .add({ waterLevel: waterLevel.high }, 1)
  .add({ disease: disease.brownSpot }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("นางฉลอง", riceType.sticky, scorer()
  .add({ area: area.floating }, 1)
  .add({ region: region.middle }, 1)
  .add({ waterLevel: waterLevel.high }, 1)
  .add({ either: [{ disease: disease.brownSpot }, { disease: disease.blast }] }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("ปิ่นแก้ว 56", riceType.paddy, scorer()
  .add({ area: area.floating }, 1)
  .add({ region: region.middle }, 1)
  .add({ waterLevel: waterLevel.high }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("พลายงามปราจีนบุรี", riceType.paddy, scorer()
  .add({ area: area.floating }, 1)
  .add({ either: [{ region: region.north }, { region: region.middle }] }, 1)
  .add({ waterLevel: waterLevel.high }, 1)
  .add({ disease: disease.blast }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("เล็บมือนาง 111", riceType.paddy, scorer()
  .add({ area: area.floating }, 1)
  .add({ region: region.middle }, 1)
  .add({ waterLevel: waterLevel.high }, 1)
  .add({ disease: disease.brownSpot }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("ขาวบ้านนา 432", riceType.paddy, scorer()
  .add({ area: area.floating }, 1)
  .add({ either: [{ region: region.east }, { region: region.middle }] }, 1)
  .add({ waterLevel: waterLevel.high }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("กข 19", riceType.paddy, scorer()
  .add({ area: area.deepwater }, 1)
  .add({ region: region.middle }, 1)
  .add({ waterLevel: waterLevel.high }, 1)
  .add({ disease: disease.bacterialBlight }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("กข 45", riceType.paddy, scorer()
  .add({ either: [{ area: area.rainfedLowland }, { area: area.deepwater }] }, 1)
  .add({ either: [{ region: region.middle }, { region: region.east }] }, 1)
  .add({ waterLevel: waterLevel.high }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("หันตรา 60", riceType.paddy, scorer()
  .add({ area: area.deepwater }, 1)
  .add({ region: region.middle }, 1)
  .add({ either: [{ waterLevel: waterLevel.high }, { waterLevel: waterLevel.low }] }, 1)
  .add({ disease: disease.blast }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("ปราจีนบุรี 1", riceType.paddy, scorer()
  .add({ area: area.deepwater }, 1)
  .add({ either: [{ region: region.middle }, { region: region.east }, { region: region.north }] }, 1)
  .add({ waterLevel: waterLevel.high }, 1)
  .add({ either: [{ disease: disease.blast }, { disease: disease.bacterialLeafStreak }] }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("ปราจีนบุรี 2", riceType.paddy, scorer()
  .add({ area: area.deepwater }, 1)
  .add({ either: [{ region: region.middle }, { region: region.east }] }, 1)
  .add({ waterLevel: waterLevel.high }, 1)
  .add({ either: [{ disease: disease.blast }, { disease: disease.bacterialBlight }] }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("อยุธยา 1", riceType.paddy, scorer()
  .add({ area: area.deepwater }, 1)
  .add({ either: [{ region: region.middle }, { region: region.east }, { region: region.north }] }, 1)
  .add({ waterLevel: waterLevel.high }, 1)
  .add({ either: [{ pest: pest.greenLeafhopper }, { pest: pest.brownPlanthopper }] }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("กข17", riceType.paddy, scorer()
  .add({ area: area.deepwater }, 1)
  .add({ either: [{ region: region.middle }, { region: region.northeast }] }, 1)
  .add({ either: [{ waterLevel: waterLevel.high }, { waterLevel: waterLevel.low }] }, 1)
  .add({ disease: disease.bacterialBlight }, 1)
  .add({ inSeason: inSeason.no }, 1)
  .build()
)

addRice("กู้เมืองหลวง", riceType.paddy, scorer()
  .add({ area: area.upland }, 1)
  .add({ region: region.south }, 1)
  .add({ waterLevel: waterLevel.low }, 1)
  .add({ pest: pest.greenLeafhopper }, 1)
  .add({ either: [{ disease: disease.blast }, { disease: disease.brownSpot }, { disease: disease.narrowBrownSpot }] }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("ขาวโป่งไคร้", riceType.sticky, scorer()
  .add({ either: [{ area: area.upland }, { area: area.highland }] }, 1)
  .add({ region: region.north }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ either: [{ disease: disease.blast }, { disease: disease.bacterialBlight }] }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("เจ้าฮ่อ", riceType.paddy, scorer()
  .add({ area: area.upland }, 1)
  .add({ either: [{ region: region.middle }, { region: region.north }] }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ either: [{ disease: disease.gallDwarf }, { disease: disease.blast }] }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("ซิวแม่จัน", riceType.sticky, scorer()
  .add({ area: area.upland }, 1)
  .add({ either: [{ region: region.northeast }, { region: region.north }] }, 1)
  .add({ waterLevel: waterLevel.low }, 1)
  .add({ disease: disease.blast }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("ดอกพะยอม", riceType.paddy, scorer()
  .add({ area: area.upland }, 1)
  .add({ region: region.south }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ either: [{ disease: disease.blast }, { disease: disease.brownSpot }, { disease: disease.narrowBrownSpot }] }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("น้ำรู", riceType.paddy, scorer()
  .add({ either: [{ area: area.upland }, { area: area.highland }] }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ either: [{ disease: disease.blast }, { disease: disease.dirtyPanicle }] }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("เจ้าลีซอสันป่าตอง", riceType.paddy, scorer()
  .add({ either: [{ area: area.upland }, { area: area.highland }] }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ disease: disease.blast }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("เจ้าขาวเชียงใหม่", riceType.paddy, scorer()
  .add({ either: [{ area: area.upland }, { area: area.highland }] }, 1)
  .add({ region: region.north }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ disease: disease.blast }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("ข้าวเหนียวลืมผัว", riceType.sticky, scorer()
  .add({ area: area.upland }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("อาร์ 258", riceType.sticky, scorer()
  .add({ area: area.upland }, 1)
  .add({ either: [{ region: region.north }, { region: region.northeast }] }, 1)
  .add({ waterLevel: waterLevel.low }, 1)
  .add({ disease: disease.blast }, 1)
  .add({ inSeason: inSeason.no }, 1)
  .build()
)

addRice("ข้าวหอมแดง", riceType.paddy, scorer()
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ pest: pest.blast }, 1)
  .add({ disease: disease.blast }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("สังข์หยดพัทลุง", riceType.paddy, scorer()
  .add({ province: province.phatthalung })
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ inSeason: inSeason.yes }, 1)
  .build()
)

addRice("ข้าวหอมกุหลาบแดง", riceType.paddy, scorer()
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ inSeason: inSeason.no }, 1)
  .build()
)

addRice("กวก. 1", riceType.japanese, scorer()
  .add({ either: [{ region: region.north }, { region: region.northeast }] }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ inSeason: inSeason.no }, 1)
  .build()
)

addRice("กวก. 2", riceType.japanese, scorer()
  .add({ region: region.north }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ inSeason: inSeason.no }, 1)
  .build()
)

addRice("สะเมิง 1 (ข้าวบาร์เลย์)", riceType.barley, scorer()
  .add({ region: region.north }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .build()
)

addRice("สะเมิง 2 (ข้าวบาร์เลย์)", riceType.barley, scorer()
  .add({ region: region.north }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .build()
)

addRice("ซีพี 304", riceType.paddy, scorer()
  .add({ area: area.irrigatedLowland }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ disease: disease.blast }, 1)
  .add({ inSeason: inSeason.no }, 1)
  .build()
)

addRice("กขผ 1", riceType.paddy, scorer()
  .add({ area: area.irrigatedLowland }, 1)
  .add({ either: [{ region: region.middle }, { region: region.north }] }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ pest: pest.whitebackPlanthopper }, 1)
  .add({ disease: disease.blast }, 1)
  .add({ inSeason: inSeason.no }, 1)
  .build()
)

addRice("กขผ 3", riceType.paddy, scorer()
  .add({ area: area.irrigatedLowland }, 1)
  .add({ region: region.middle }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ pest: pest.whitebackPlanthopper }, 1)
  .add({ disease: disease.blast }, 1)
  .add({ inSeason: inSeason.no }, 1)
  .build()
)

addRice("สะเมิง 1 (ข้าวสาลี)", riceType.wheat, scorer()
  .add({ region: region.middle }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .add({ disease: disease.rust }, 1)
  .build()
)

addRice("สะเมิง 2 (ข้าวสาลี)", riceType.wheat, scorer()
  .add({ region: region.middle }, 1)
  .add({ waterLevel: waterLevel.average }, 1)
  .build()
)

addRice("แพร่ 60", riceType.wheat, scorer()
  .add({ either: [{ region: region.north }, { region: region.northeast }] }, 1)
  .add({ waterLevel: waterLevel.low }, 1)
  .add({ disease: disease.rust }, 1)
  .build()
)

addRice("ฝาง 60", riceType.wheat, scorer()
  .add({ either: [{ area: area.irrigatedLowland, area: area.rainfedLowland }] }, 1)
  .add({ either: [{ region: region.north }, { region: region.northeast }] }, 1)
  .add({ waterLevel: waterLevel.low }, 1)
  .add({ disease: disease.rust }, 1)
  .build()
)